/** 与主画面保持相同的静态 SVG 图标，用于图标编辑预览。 */
export function DefaultHomeIcon({kind,iconKey}:{kind:'app'|'dock';iconKey:string}){switch(kind+':'+iconKey){
case "app:ledger": return <svg className="px-icon" viewBox="0 0 16 16" aria-hidden="true" shapeRendering="crispEdges">
                  <rect className="px-x" x="5" y="0" width="5" height="1" />
                  <rect className="px-x" x="3" y="1" width="2" height="1" />
                  <rect className="px-o" x="5" y="1" width="5" height="1" />
                  <rect className="px-x" x="10" y="1" width="2" height="1" />
                  <rect className="px-x" x="2" y="2" width="1" height="1" />
                  <rect className="px-o" x="3" y="2" width="9" height="1" />
                  <rect className="px-x" x="12" y="2" width="1" height="1" />
                  <rect className="px-x" x="1" y="3" width="1" height="1" />
                  <rect className="px-o" x="2" y="3" width="11" height="1" />
                  <rect className="px-x" x="13" y="3" width="1" height="1" />
                  <rect className="px-x" x="1" y="4" width="1" height="1" />
                  <rect className="px-o" x="2" y="4" width="2" height="1" />
                  <rect className="px-x" x="4" y="4" width="2" height="1" />
                  <rect className="px-o" x="6" y="4" width="3" height="1" />
                  <rect className="px-x" x="9" y="4" width="2" height="1" />
                  <rect className="px-o" x="11" y="4" width="2" height="1" />
                  <rect className="px-x" x="13" y="4" width="1" height="1" />
                  <rect className="px-x" x="0" y="5" width="1" height="1" />
                  <rect className="px-o" x="1" y="5" width="4" height="1" />
                  <rect className="px-x" x="5" y="5" width="2" height="1" />
                  <rect className="px-o" x="7" y="5" width="1" height="1" />
                  <rect className="px-x" x="8" y="5" width="2" height="1" />
                  <rect className="px-o" x="10" y="5" width="4" height="1" />
                  <rect className="px-x" x="14" y="5" width="1" height="1" />
                  <rect className="px-x" x="0" y="6" width="1" height="1" />
                  <rect className="px-o" x="1" y="6" width="5" height="1" />
                  <rect className="px-x" x="6" y="6" width="3" height="1" />
                  <rect className="px-o" x="9" y="6" width="5" height="1" />
                  <rect className="px-x" x="14" y="6" width="1" height="1" />
                  <rect className="px-x" x="0" y="7" width="1" height="1" />
                  <rect className="px-o" x="1" y="7" width="3" height="1" />
                  <rect className="px-x" x="4" y="7" width="7" height="1" />
                  <rect className="px-o" x="11" y="7" width="3" height="1" />
                  <rect className="px-x" x="14" y="7" width="1" height="1" />
                  <rect className="px-x" x="0" y="8" width="1" height="1" />
                  <rect className="px-o" x="1" y="8" width="6" height="1" />
                  <rect className="px-x" x="7" y="8" width="1" height="1" />
                  <rect className="px-o" x="8" y="8" width="6" height="1" />
                  <rect className="px-x" x="14" y="8" width="1" height="1" />
                  <rect className="px-x" x="0" y="9" width="1" height="1" />
                  <rect className="px-o" x="1" y="9" width="3" height="1" />
                  <rect className="px-x" x="4" y="9" width="7" height="1" />
                  <rect className="px-o" x="11" y="9" width="3" height="1" />
                  <rect className="px-x" x="14" y="9" width="1" height="1" />
                  <rect className="px-x" x="1" y="10" width="1" height="1" />
                  <rect className="px-o" x="2" y="10" width="5" height="1" />
                  <rect className="px-x" x="7" y="10" width="1" height="1" />
                  <rect className="px-o" x="8" y="10" width="5" height="1" />
                  <rect className="px-x" x="13" y="10" width="1" height="1" />
                  <rect className="px-x" x="1" y="11" width="1" height="1" />
                  <rect className="px-o" x="2" y="11" width="5" height="1" />
                  <rect className="px-x" x="7" y="11" width="1" height="1" />
                  <rect className="px-o" x="8" y="11" width="5" height="1" />
                  <rect className="px-x" x="13" y="11" width="1" height="1" />
                  <rect className="px-x" x="2" y="12" width="1" height="1" />
                  <rect className="px-o" x="3" y="12" width="9" height="1" />
                  <rect className="px-x" x="12" y="12" width="1" height="1" />
                  <rect className="px-x" x="3" y="13" width="2" height="1" />
                  <rect className="px-o" x="5" y="13" width="5" height="1" />
                  <rect className="px-x" x="10" y="13" width="2" height="1" />
                  <rect className="px-x" x="5" y="14" width="5" height="1" />
                </svg>;
case "app:memos": return <svg className="px-icon" viewBox="0 0 16 16" aria-hidden="true" shapeRendering="crispEdges">
                  <rect className="px-x" x="1" y="1" width="14" height="1" />
                  <rect className="px-x" x="1" y="2" width="1" height="1" />
                  <rect className="px-o" x="2" y="2" width="12" height="1" />
                  <rect className="px-x" x="14" y="2" width="1" height="1" />
                  <rect className="px-x" x="1" y="3" width="1" height="1" />
                  <rect className="px-w" x="2" y="3" width="1" height="1" />
                  <rect className="px-x" x="3" y="3" width="3" height="1" />
                  <rect className="px-w" x="6" y="3" width="8" height="1" />
                  <rect className="px-x" x="14" y="3" width="1" height="1" />
                  <rect className="px-x" x="1" y="4" width="1" height="1" />
                  <rect className="px-w" x="2" y="4" width="1" height="1" />
                  <rect className="px-x" x="3" y="4" width="1" height="1" />
                  <rect className="px-o" x="4" y="4" width="1" height="1" />
                  <rect className="px-x" x="5" y="4" width="1" height="1" />
                  <rect className="px-w" x="6" y="4" width="1" height="1" />
                  <rect className="px-x" x="7" y="4" width="6" height="1" />
                  <rect className="px-w" x="13" y="4" width="1" height="1" />
                  <rect className="px-x" x="14" y="4" width="1" height="1" />
                  <rect className="px-x" x="1" y="5" width="1" height="1" />
                  <rect className="px-w" x="2" y="5" width="1" height="1" />
                  <rect className="px-x" x="3" y="5" width="3" height="1" />
                  <rect className="px-w" x="6" y="5" width="8" height="1" />
                  <rect className="px-x" x="14" y="5" width="1" height="1" />
                  <rect className="px-x" x="1" y="6" width="1" height="1" />
                  <rect className="px-w" x="2" y="6" width="12" height="1" />
                  <rect className="px-x" x="14" y="6" width="1" height="1" />
                  <rect className="px-x" x="1" y="7" width="1" height="1" />
                  <rect className="px-w" x="2" y="7" width="1" height="1" />
                  <rect className="px-x" x="3" y="7" width="3" height="1" />
                  <rect className="px-w" x="6" y="7" width="8" height="1" />
                  <rect className="px-x" x="14" y="7" width="1" height="1" />
                  <rect className="px-x" x="1" y="8" width="1" height="1" />
                  <rect className="px-w" x="2" y="8" width="1" height="1" />
                  <rect className="px-x" x="3" y="8" width="1" height="1" />
                  <rect className="px-o" x="4" y="8" width="1" height="1" />
                  <rect className="px-x" x="5" y="8" width="1" height="1" />
                  <rect className="px-w" x="6" y="8" width="1" height="1" />
                  <rect className="px-x" x="7" y="8" width="6" height="1" />
                  <rect className="px-w" x="13" y="8" width="1" height="1" />
                  <rect className="px-x" x="14" y="8" width="1" height="1" />
                  <rect className="px-x" x="1" y="9" width="1" height="1" />
                  <rect className="px-w" x="2" y="9" width="1" height="1" />
                  <rect className="px-x" x="3" y="9" width="3" height="1" />
                  <rect className="px-w" x="6" y="9" width="8" height="1" />
                  <rect className="px-x" x="14" y="9" width="1" height="1" />
                  <rect className="px-x" x="1" y="10" width="1" height="1" />
                  <rect className="px-w" x="2" y="10" width="12" height="1" />
                  <rect className="px-x" x="14" y="10" width="1" height="1" />
                  <rect className="px-x" x="1" y="11" width="1" height="1" />
                  <rect className="px-w" x="2" y="11" width="1" height="1" />
                  <rect className="px-x" x="3" y="11" width="3" height="1" />
                  <rect className="px-w" x="6" y="11" width="8" height="1" />
                  <rect className="px-x" x="14" y="11" width="1" height="1" />
                  <rect className="px-x" x="1" y="12" width="1" height="1" />
                  <rect className="px-w" x="2" y="12" width="1" height="1" />
                  <rect className="px-x" x="3" y="12" width="1" height="1" />
                  <rect className="px-o" x="4" y="12" width="1" height="1" />
                  <rect className="px-x" x="5" y="12" width="1" height="1" />
                  <rect className="px-w" x="6" y="12" width="1" height="1" />
                  <rect className="px-x" x="7" y="12" width="4" height="1" />
                  <rect className="px-w" x="11" y="12" width="3" height="1" />
                  <rect className="px-x" x="14" y="12" width="1" height="1" />
                  <rect className="px-x" x="1" y="13" width="1" height="1" />
                  <rect className="px-w" x="2" y="13" width="1" height="1" />
                  <rect className="px-x" x="3" y="13" width="3" height="1" />
                  <rect className="px-w" x="6" y="13" width="8" height="1" />
                  <rect className="px-x" x="14" y="13" width="1" height="1" />
                  <rect className="px-x" x="1" y="14" width="14" height="1" />
                </svg>;
case "app:world": return <svg className="px-icon" viewBox="0 0 16 16" aria-hidden="true" shapeRendering="crispEdges">
                  <rect className="px-x" x="5" y="0" width="5" height="1" />
                  <rect className="px-x" x="3" y="1" width="2" height="1" />
                  <rect className="px-o" x="5" y="1" width="1" height="1" />
                  <rect className="px-x" x="6" y="1" width="1" height="1" />
                  <rect className="px-o" x="7" y="1" width="1" height="1" />
                  <rect className="px-x" x="8" y="1" width="1" height="1" />
                  <rect className="px-o" x="9" y="1" width="1" height="1" />
                  <rect className="px-x" x="10" y="1" width="2" height="1" />
                  <rect className="px-x" x="2" y="2" width="1" height="1" />
                  <rect className="px-o" x="3" y="2" width="2" height="1" />
                  <rect className="px-x" x="5" y="2" width="1" height="1" />
                  <rect className="px-o" x="6" y="2" width="3" height="1" />
                  <rect className="px-x" x="9" y="2" width="1" height="1" />
                  <rect className="px-o" x="10" y="2" width="2" height="1" />
                  <rect className="px-x" x="12" y="2" width="1" height="1" />
                  <rect className="px-x" x="1" y="3" width="1" height="1" />
                  <rect className="px-o" x="2" y="3" width="2" height="1" />
                  <rect className="px-x" x="4" y="3" width="1" height="1" />
                  <rect className="px-o" x="5" y="3" width="5" height="1" />
                  <rect className="px-x" x="10" y="3" width="1" height="1" />
                  <rect className="px-o" x="11" y="3" width="2" height="1" />
                  <rect className="px-x" x="13" y="3" width="1" height="1" />
                  <rect className="px-x" x="1" y="4" width="1" height="1" />
                  <rect className="px-o" x="2" y="4" width="2" height="1" />
                  <rect className="px-x" x="4" y="4" width="1" height="1" />
                  <rect className="px-o" x="5" y="4" width="5" height="1" />
                  <rect className="px-x" x="10" y="4" width="1" height="1" />
                  <rect className="px-o" x="11" y="4" width="2" height="1" />
                  <rect className="px-x" x="13" y="4" width="1" height="1" />
                  <rect className="px-x" x="0" y="5" width="1" height="1" />
                  <rect className="px-o" x="1" y="5" width="3" height="1" />
                  <rect className="px-x" x="4" y="5" width="1" height="1" />
                  <rect className="px-o" x="5" y="5" width="5" height="1" />
                  <rect className="px-x" x="10" y="5" width="1" height="1" />
                  <rect className="px-o" x="11" y="5" width="3" height="1" />
                  <rect className="px-x" x="14" y="5" width="1" height="1" />
                  <rect className="px-x" x="0" y="6" width="1" height="1" />
                  <rect className="px-o" x="1" y="6" width="3" height="1" />
                  <rect className="px-x" x="4" y="6" width="1" height="1" />
                  <rect className="px-o" x="5" y="6" width="5" height="1" />
                  <rect className="px-x" x="10" y="6" width="1" height="1" />
                  <rect className="px-o" x="11" y="6" width="3" height="1" />
                  <rect className="px-x" x="14" y="6" width="1" height="1" />
                  <rect className="px-x" x="0" y="7" width="15" height="1" />
                  <rect className="px-x" x="0" y="8" width="1" height="1" />
                  <rect className="px-o" x="1" y="8" width="3" height="1" />
                  <rect className="px-x" x="4" y="8" width="1" height="1" />
                  <rect className="px-o" x="5" y="8" width="5" height="1" />
                  <rect className="px-x" x="10" y="8" width="1" height="1" />
                  <rect className="px-o" x="11" y="8" width="3" height="1" />
                  <rect className="px-x" x="14" y="8" width="1" height="1" />
                  <rect className="px-x" x="0" y="9" width="1" height="1" />
                  <rect className="px-o" x="1" y="9" width="3" height="1" />
                  <rect className="px-x" x="4" y="9" width="1" height="1" />
                  <rect className="px-o" x="5" y="9" width="5" height="1" />
                  <rect className="px-x" x="10" y="9" width="1" height="1" />
                  <rect className="px-o" x="11" y="9" width="3" height="1" />
                  <rect className="px-x" x="14" y="9" width="1" height="1" />
                  <rect className="px-x" x="1" y="10" width="1" height="1" />
                  <rect className="px-o" x="2" y="10" width="2" height="1" />
                  <rect className="px-x" x="4" y="10" width="1" height="1" />
                  <rect className="px-o" x="5" y="10" width="5" height="1" />
                  <rect className="px-x" x="10" y="10" width="1" height="1" />
                  <rect className="px-o" x="11" y="10" width="2" height="1" />
                  <rect className="px-x" x="13" y="10" width="1" height="1" />
                  <rect className="px-x" x="1" y="11" width="1" height="1" />
                  <rect className="px-o" x="2" y="11" width="2" height="1" />
                  <rect className="px-x" x="4" y="11" width="1" height="1" />
                  <rect className="px-o" x="5" y="11" width="5" height="1" />
                  <rect className="px-x" x="10" y="11" width="1" height="1" />
                  <rect className="px-o" x="11" y="11" width="2" height="1" />
                  <rect className="px-x" x="13" y="11" width="1" height="1" />
                  <rect className="px-x" x="2" y="12" width="1" height="1" />
                  <rect className="px-o" x="3" y="12" width="2" height="1" />
                  <rect className="px-x" x="5" y="12" width="1" height="1" />
                  <rect className="px-o" x="6" y="12" width="3" height="1" />
                  <rect className="px-x" x="9" y="12" width="1" height="1" />
                  <rect className="px-o" x="10" y="12" width="2" height="1" />
                  <rect className="px-x" x="12" y="12" width="1" height="1" />
                  <rect className="px-x" x="3" y="13" width="2" height="1" />
                  <rect className="px-o" x="5" y="13" width="1" height="1" />
                  <rect className="px-x" x="6" y="13" width="1" height="1" />
                  <rect className="px-o" x="7" y="13" width="1" height="1" />
                  <rect className="px-x" x="8" y="13" width="1" height="1" />
                  <rect className="px-o" x="9" y="13" width="1" height="1" />
                  <rect className="px-x" x="10" y="13" width="2" height="1" />
                  <rect className="px-x" x="5" y="14" width="5" height="1" />
                </svg>;
case "app:memories": return <svg className="px-icon" viewBox="0 0 16 16" aria-hidden="true" shapeRendering="crispEdges">
                  <rect className="px-l" x="9" y="1" width="6" height="1" />
                  <rect className="px-x" x="15" y="1" width="1" height="1" />
                  <rect className="px-l" x="2" y="2" width="11" height="1" />
                  <rect className="px-o" x="13" y="2" width="2" height="1" />
                  <rect className="px-x" x="15" y="2" width="1" height="1" />
                  <rect className="px-l" x="2" y="3" width="1" height="1" />
                  <rect className="px-w" x="3" y="3" width="9" height="1" />
                  <rect className="px-l" x="12" y="3" width="1" height="1" />
                  <rect className="px-o" x="13" y="3" width="2" height="1" />
                  <rect className="px-x" x="15" y="3" width="1" height="1" />
                  <rect className="px-l" x="1" y="4" width="12" height="1" />
                  <rect className="px-o" x="13" y="4" width="2" height="1" />
                  <rect className="px-x" x="15" y="4" width="1" height="1" />
                  <rect className="px-l" x="0" y="5" width="1" height="1" />
                  <rect className="px-o" x="1" y="5" width="12" height="1" />
                  <rect className="px-l" x="13" y="5" width="1" height="1" />
                  <rect className="px-o" x="14" y="5" width="1" height="1" />
                  <rect className="px-x" x="15" y="5" width="1" height="1" />
                  <rect className="px-l" x="0" y="6" width="1" height="1" />
                  <rect className="px-o" x="1" y="6" width="12" height="1" />
                  <rect className="px-l" x="13" y="6" width="1" height="1" />
                  <rect className="px-o" x="14" y="6" width="1" height="1" />
                  <rect className="px-x" x="15" y="6" width="1" height="1" />
                  <rect className="px-l" x="0" y="7" width="1" height="1" />
                  <rect className="px-o" x="1" y="7" width="12" height="1" />
                  <rect className="px-l" x="13" y="7" width="1" height="1" />
                  <rect className="px-o" x="14" y="7" width="1" height="1" />
                  <rect className="px-x" x="15" y="7" width="1" height="1" />
                  <rect className="px-l" x="1" y="8" width="1" height="1" />
                  <rect className="px-o" x="2" y="8" width="13" height="1" />
                  <rect className="px-x" x="15" y="8" width="1" height="1" />
                  <rect className="px-l" x="1" y="9" width="1" height="1" />
                  <rect className="px-o" x="2" y="9" width="12" height="1" />
                  <rect className="px-l" x="14" y="9" width="1" height="1" />
                  <rect className="px-x" x="15" y="9" width="1" height="1" />
                  <rect className="px-l" x="1" y="10" width="1" height="1" />
                  <rect className="px-o" x="2" y="10" width="12" height="1" />
                  <rect className="px-l" x="14" y="10" width="1" height="1" />
                  <rect className="px-x" x="15" y="10" width="1" height="1" />
                  <rect className="px-l" x="1" y="11" width="1" height="1" />
                  <rect className="px-o" x="2" y="11" width="12" height="1" />
                  <rect className="px-l" x="14" y="11" width="1" height="1" />
                  <rect className="px-x" x="15" y="11" width="1" height="1" />
                  <rect className="px-l" x="2" y="12" width="1" height="1" />
                  <rect className="px-o" x="3" y="12" width="12" height="1" />
                  <rect className="px-x" x="15" y="12" width="1" height="1" />
                  <rect className="px-x" x="2" y="13" width="14" height="1" />
                </svg>;
case "dock:home": return <svg className="px-icon" viewBox="0 0 16 16" aria-hidden="true" shapeRendering="crispEdges">
          <rect className="px-x" x="7" y="1" width="1" height="1" />
          <rect className="px-x" x="6" y="2" width="3" height="1" />
          <rect className="px-x" x="11" y="2" width="1" height="1" />
          <rect className="px-x" x="5" y="3" width="2" height="1" />
          <rect className="px-o" x="7" y="3" width="1" height="1" />
          <rect className="px-x" x="8" y="3" width="2" height="1" />
          <rect className="px-x" x="11" y="3" width="1" height="1" />
          <rect className="px-x" x="4" y="4" width="2" height="1" />
          <rect className="px-o" x="6" y="4" width="3" height="1" />
          <rect className="px-x" x="9" y="4" width="3" height="1" />
          <rect className="px-x" x="3" y="5" width="2" height="1" />
          <rect className="px-o" x="5" y="5" width="5" height="1" />
          <rect className="px-x" x="10" y="5" width="2" height="1" />
          <rect className="px-x" x="2" y="6" width="2" height="1" />
          <rect className="px-o" x="4" y="6" width="7" height="1" />
          <rect className="px-x" x="11" y="6" width="2" height="1" />
          <rect className="px-x" x="1" y="7" width="2" height="1" />
          <rect className="px-o" x="3" y="7" width="9" height="1" />
          <rect className="px-x" x="12" y="7" width="2" height="1" />
          <rect className="px-x" x="0" y="8" width="2" height="1" />
          <rect className="px-o" x="2" y="8" width="11" height="1" />
          <rect className="px-x" x="13" y="8" width="2" height="1" />
          <rect className="px-x" x="1" y="9" width="1" height="1" />
          <rect className="px-o" x="2" y="9" width="3" height="1" />
          <rect className="px-x" x="5" y="9" width="5" height="1" />
          <rect className="px-o" x="10" y="9" width="3" height="1" />
          <rect className="px-x" x="13" y="9" width="1" height="1" />
          <rect className="px-x" x="1" y="10" width="1" height="1" />
          <rect className="px-o" x="2" y="10" width="3" height="1" />
          <rect className="px-x" x="5" y="10" width="1" height="1" />
          <rect className="px-w" x="6" y="10" width="3" height="1" />
          <rect className="px-x" x="9" y="10" width="1" height="1" />
          <rect className="px-o" x="10" y="10" width="3" height="1" />
          <rect className="px-x" x="13" y="10" width="1" height="1" />
          <rect className="px-x" x="1" y="11" width="1" height="1" />
          <rect className="px-o" x="2" y="11" width="3" height="1" />
          <rect className="px-x" x="5" y="11" width="1" height="1" />
          <rect className="px-w" x="6" y="11" width="3" height="1" />
          <rect className="px-x" x="9" y="11" width="1" height="1" />
          <rect className="px-o" x="10" y="11" width="3" height="1" />
          <rect className="px-x" x="13" y="11" width="1" height="1" />
          <rect className="px-x" x="1" y="12" width="1" height="1" />
          <rect className="px-o" x="2" y="12" width="3" height="1" />
          <rect className="px-x" x="5" y="12" width="1" height="1" />
          <rect className="px-w" x="6" y="12" width="3" height="1" />
          <rect className="px-x" x="9" y="12" width="1" height="1" />
          <rect className="px-o" x="10" y="12" width="3" height="1" />
          <rect className="px-x" x="13" y="12" width="1" height="1" />
          <rect className="px-x" x="1" y="13" width="13" height="1" />
        </svg>;
case "dock:chat": return <svg className="px-icon" viewBox="0 0 16 16" aria-hidden="true" shapeRendering="crispEdges">
          <rect className="px-x" x="3" y="2" width="10" height="1" />
          <rect className="px-x" x="2" y="3" width="1" height="1" />
          <rect className="px-o" x="3" y="3" width="10" height="1" />
          <rect className="px-x" x="13" y="3" width="1" height="1" />
          <rect className="px-x" x="1" y="4" width="1" height="1" />
          <rect className="px-o" x="2" y="4" width="12" height="1" />
          <rect className="px-x" x="14" y="4" width="1" height="1" />
          <rect className="px-x" x="1" y="5" width="1" height="1" />
          <rect className="px-o" x="2" y="5" width="12" height="1" />
          <rect className="px-x" x="14" y="5" width="1" height="1" />
          <rect className="px-x" x="1" y="6" width="1" height="1" />
          <rect className="px-o" x="2" y="6" width="12" height="1" />
          <rect className="px-x" x="14" y="6" width="1" height="1" />
          <rect className="px-x" x="1" y="7" width="1" height="1" />
          <rect className="px-o" x="2" y="7" width="12" height="1" />
          <rect className="px-x" x="14" y="7" width="1" height="1" />
          <rect className="px-x" x="1" y="8" width="1" height="1" />
          <rect className="px-o" x="2" y="8" width="12" height="1" />
          <rect className="px-x" x="14" y="8" width="1" height="1" />
          <rect className="px-x" x="1" y="9" width="1" height="1" />
          <rect className="px-o" x="2" y="9" width="12" height="1" />
          <rect className="px-x" x="14" y="9" width="1" height="1" />
          <rect className="px-x" x="2" y="10" width="1" height="1" />
          <rect className="px-o" x="3" y="10" width="10" height="1" />
          <rect className="px-x" x="13" y="10" width="1" height="1" />
          <rect className="px-x" x="3" y="11" width="3" height="1" />
          <rect className="px-o" x="6" y="11" width="2" height="1" />
          <rect className="px-x" x="8" y="11" width="5" height="1" />
          <rect className="px-x" x="6" y="12" width="1" height="1" />
          <rect className="px-o" x="7" y="12" width="1" height="1" />
          <rect className="px-x" x="8" y="12" width="1" height="1" />
          <rect className="px-x" x="6" y="13" width="2" height="1" />
        </svg>;
case "dock:diary": return <svg className="px-icon" viewBox="0 0 16 16" aria-hidden="true" shapeRendering="crispEdges">
          <rect className="px-x" x="3" y="1" width="11" height="1" />
          <rect className="px-x" x="2" y="2" width="1" height="1" />
          <rect className="px-o" x="3" y="2" width="1" height="1" />
          <rect className="px-x" x="4" y="2" width="1" height="1" />
          <rect className="px-o" x="5" y="2" width="8" height="1" />
          <rect className="px-x" x="13" y="2" width="1" height="1" />
          <rect className="px-x" x="2" y="3" width="1" height="1" />
          <rect className="px-o" x="3" y="3" width="1" height="1" />
          <rect className="px-x" x="4" y="3" width="1" height="1" />
          <rect className="px-o" x="5" y="3" width="1" height="1" />
          <rect className="px-x" x="6" y="3" width="6" height="1" />
          <rect className="px-o" x="12" y="3" width="1" height="1" />
          <rect className="px-x" x="13" y="3" width="1" height="1" />
          <rect className="px-x" x="2" y="4" width="1" height="1" />
          <rect className="px-o" x="3" y="4" width="1" height="1" />
          <rect className="px-x" x="4" y="4" width="1" height="1" />
          <rect className="px-o" x="5" y="4" width="1" height="1" />
          <rect className="px-x" x="6" y="4" width="1" height="1" />
          <rect className="px-w" x="7" y="4" width="4" height="1" />
          <rect className="px-x" x="11" y="4" width="1" height="1" />
          <rect className="px-o" x="12" y="4" width="1" height="1" />
          <rect className="px-x" x="13" y="4" width="1" height="1" />
          <rect className="px-x" x="2" y="5" width="1" height="1" />
          <rect className="px-o" x="3" y="5" width="1" height="1" />
          <rect className="px-x" x="4" y="5" width="1" height="1" />
          <rect className="px-o" x="5" y="5" width="1" height="1" />
          <rect className="px-x" x="6" y="5" width="6" height="1" />
          <rect className="px-o" x="12" y="5" width="1" height="1" />
          <rect className="px-x" x="13" y="5" width="1" height="1" />
          <rect className="px-x" x="2" y="6" width="1" height="1" />
          <rect className="px-o" x="3" y="6" width="1" height="1" />
          <rect className="px-x" x="4" y="6" width="1" height="1" />
          <rect className="px-o" x="5" y="6" width="8" height="1" />
          <rect className="px-x" x="13" y="6" width="1" height="1" />
          <rect className="px-x" x="2" y="7" width="1" height="1" />
          <rect className="px-o" x="3" y="7" width="1" height="1" />
          <rect className="px-x" x="4" y="7" width="1" height="1" />
          <rect className="px-o" x="5" y="7" width="8" height="1" />
          <rect className="px-x" x="13" y="7" width="1" height="1" />
          <rect className="px-x" x="2" y="8" width="1" height="1" />
          <rect className="px-o" x="3" y="8" width="1" height="1" />
          <rect className="px-x" x="4" y="8" width="1" height="1" />
          <rect className="px-o" x="5" y="8" width="8" height="1" />
          <rect className="px-x" x="13" y="8" width="1" height="1" />
          <rect className="px-x" x="2" y="9" width="1" height="1" />
          <rect className="px-o" x="3" y="9" width="1" height="1" />
          <rect className="px-x" x="4" y="9" width="1" height="1" />
          <rect className="px-o" x="5" y="9" width="8" height="1" />
          <rect className="px-x" x="13" y="9" width="1" height="1" />
          <rect className="px-x" x="2" y="10" width="1" height="1" />
          <rect className="px-o" x="3" y="10" width="1" height="1" />
          <rect className="px-x" x="4" y="10" width="1" height="1" />
          <rect className="px-o" x="5" y="10" width="8" height="1" />
          <rect className="px-x" x="13" y="10" width="1" height="1" />
          <rect className="px-x" x="2" y="11" width="1" height="1" />
          <rect className="px-o" x="3" y="11" width="1" height="1" />
          <rect className="px-x" x="4" y="11" width="1" height="1" />
          <rect className="px-o" x="5" y="11" width="8" height="1" />
          <rect className="px-x" x="13" y="11" width="1" height="1" />
          <rect className="px-x" x="2" y="12" width="1" height="1" />
          <rect className="px-o" x="3" y="12" width="1" height="1" />
          <rect className="px-x" x="4" y="12" width="10" height="1" />
          <rect className="px-x" x="2" y="13" width="1" height="1" />
          <rect className="px-o" x="3" y="13" width="1" height="1" />
          <rect className="px-w" x="4" y="13" width="9" height="1" />
          <rect className="px-x" x="13" y="13" width="1" height="1" />
          <rect className="px-x" x="3" y="14" width="11" height="1" />
        </svg>;
case "dock:space": return <svg className="px-icon" viewBox="0 0 16 16" aria-hidden="true" shapeRendering="crispEdges">
          <rect className="px-x" x="4" y="1" width="2" height="1" />
          <rect className="px-x" x="10" y="1" width="2" height="1" />
          <rect className="px-x" x="3" y="2" width="1" height="1" />
          <rect className="px-o" x="4" y="2" width="2" height="1" />
          <rect className="px-x" x="6" y="2" width="1" height="1" />
          <rect className="px-x" x="9" y="2" width="1" height="1" />
          <rect className="px-o" x="10" y="2" width="2" height="1" />
          <rect className="px-x" x="12" y="2" width="1" height="1" />
          <rect className="px-x" x="3" y="3" width="1" height="1" />
          <rect className="px-o" x="4" y="3" width="2" height="1" />
          <rect className="px-x" x="6" y="3" width="1" height="1" />
          <rect className="px-x" x="9" y="3" width="1" height="1" />
          <rect className="px-o" x="10" y="3" width="2" height="1" />
          <rect className="px-x" x="12" y="3" width="1" height="1" />
          <rect className="px-x" x="1" y="4" width="2" height="1" />
          <rect className="px-x" x="4" y="4" width="2" height="1" />
          <rect className="px-x" x="10" y="4" width="2" height="1" />
          <rect className="px-x" x="13" y="4" width="2" height="1" />
          <rect className="px-x" x="0" y="5" width="1" height="1" />
          <rect className="px-o" x="1" y="5" width="2" height="1" />
          <rect className="px-x" x="3" y="5" width="1" height="1" />
          <rect className="px-x" x="12" y="5" width="1" height="1" />
          <rect className="px-o" x="13" y="5" width="2" height="1" />
          <rect className="px-x" x="15" y="5" width="1" height="1" />
          <rect className="px-x" x="0" y="6" width="1" height="1" />
          <rect className="px-o" x="1" y="6" width="2" height="1" />
          <rect className="px-x" x="3" y="6" width="1" height="1" />
          <rect className="px-x" x="6" y="6" width="4" height="1" />
          <rect className="px-x" x="12" y="6" width="1" height="1" />
          <rect className="px-o" x="13" y="6" width="2" height="1" />
          <rect className="px-x" x="15" y="6" width="1" height="1" />
          <rect className="px-x" x="1" y="7" width="2" height="1" />
          <rect className="px-x" x="5" y="7" width="1" height="1" />
          <rect className="px-o" x="6" y="7" width="4" height="1" />
          <rect className="px-x" x="10" y="7" width="1" height="1" />
          <rect className="px-x" x="13" y="7" width="2" height="1" />
          <rect className="px-x" x="3" y="8" width="1" height="1" />
          <rect className="px-o" x="4" y="8" width="8" height="1" />
          <rect className="px-x" x="12" y="8" width="1" height="1" />
          <rect className="px-x" x="2" y="9" width="1" height="1" />
          <rect className="px-o" x="3" y="9" width="10" height="1" />
          <rect className="px-x" x="13" y="9" width="1" height="1" />
          <rect className="px-x" x="2" y="10" width="1" height="1" />
          <rect className="px-o" x="3" y="10" width="10" height="1" />
          <rect className="px-x" x="13" y="10" width="1" height="1" />
          <rect className="px-x" x="2" y="11" width="1" height="1" />
          <rect className="px-o" x="3" y="11" width="10" height="1" />
          <rect className="px-x" x="13" y="11" width="1" height="1" />
          <rect className="px-x" x="3" y="12" width="1" height="1" />
          <rect className="px-o" x="4" y="12" width="3" height="1" />
          <rect className="px-x" x="7" y="12" width="2" height="1" />
          <rect className="px-o" x="9" y="12" width="3" height="1" />
          <rect className="px-x" x="12" y="12" width="1" height="1" />
          <rect className="px-x" x="4" y="13" width="3" height="1" />
          <rect className="px-x" x="9" y="13" width="3" height="1" />
        </svg>;
case "dock:settings": return <svg className="px-icon" viewBox="0 0 16 16" aria-hidden="true" shapeRendering="crispEdges">
          <rect className="px-x" x="6" y="1" width="3" height="1" />
          <rect className="px-x" x="3" y="2" width="2" height="1" />
          <rect className="px-x" x="6" y="2" width="1" height="1" />
          <rect className="px-o" x="7" y="2" width="1" height="1" />
          <rect className="px-x" x="8" y="2" width="1" height="1" />
          <rect className="px-x" x="10" y="2" width="2" height="1" />
          <rect className="px-x" x="2" y="3" width="1" height="1" />
          <rect className="px-o" x="3" y="3" width="2" height="1" />
          <rect className="px-x" x="5" y="3" width="1" height="1" />
          <rect className="px-o" x="6" y="3" width="3" height="1" />
          <rect className="px-x" x="9" y="3" width="1" height="1" />
          <rect className="px-o" x="10" y="3" width="2" height="1" />
          <rect className="px-x" x="12" y="3" width="1" height="1" />
          <rect className="px-x" x="2" y="4" width="1" height="1" />
          <rect className="px-o" x="3" y="4" width="9" height="1" />
          <rect className="px-x" x="12" y="4" width="1" height="1" />
          <rect className="px-x" x="3" y="5" width="1" height="1" />
          <rect className="px-o" x="4" y="5" width="2" height="1" />
          <rect className="px-x" x="6" y="5" width="3" height="1" />
          <rect className="px-o" x="9" y="5" width="2" height="1" />
          <rect className="px-x" x="11" y="5" width="1" height="1" />
          <rect className="px-x" x="1" y="6" width="2" height="1" />
          <rect className="px-o" x="3" y="6" width="2" height="1" />
          <rect className="px-x" x="5" y="6" width="1" height="1" />
          <rect className="px-w" x="6" y="6" width="3" height="1" />
          <rect className="px-x" x="9" y="6" width="1" height="1" />
          <rect className="px-o" x="10" y="6" width="2" height="1" />
          <rect className="px-x" x="12" y="6" width="2" height="1" />
          <rect className="px-x" x="1" y="7" width="1" height="1" />
          <rect className="px-o" x="2" y="7" width="3" height="1" />
          <rect className="px-x" x="5" y="7" width="1" height="1" />
          <rect className="px-w" x="6" y="7" width="1" height="1" />
          <rect className="px-x" x="7" y="7" width="1" height="1" />
          <rect className="px-w" x="8" y="7" width="1" height="1" />
          <rect className="px-x" x="9" y="7" width="1" height="1" />
          <rect className="px-o" x="10" y="7" width="3" height="1" />
          <rect className="px-x" x="13" y="7" width="1" height="1" />
          <rect className="px-x" x="1" y="8" width="2" height="1" />
          <rect className="px-o" x="3" y="8" width="2" height="1" />
          <rect className="px-x" x="5" y="8" width="1" height="1" />
          <rect className="px-w" x="6" y="8" width="3" height="1" />
          <rect className="px-x" x="9" y="8" width="1" height="1" />
          <rect className="px-o" x="10" y="8" width="2" height="1" />
          <rect className="px-x" x="12" y="8" width="2" height="1" />
          <rect className="px-x" x="3" y="9" width="1" height="1" />
          <rect className="px-o" x="4" y="9" width="2" height="1" />
          <rect className="px-x" x="6" y="9" width="3" height="1" />
          <rect className="px-o" x="9" y="9" width="2" height="1" />
          <rect className="px-x" x="11" y="9" width="1" height="1" />
          <rect className="px-x" x="2" y="10" width="1" height="1" />
          <rect className="px-o" x="3" y="10" width="9" height="1" />
          <rect className="px-x" x="12" y="10" width="1" height="1" />
          <rect className="px-x" x="2" y="11" width="1" height="1" />
          <rect className="px-o" x="3" y="11" width="2" height="1" />
          <rect className="px-x" x="5" y="11" width="1" height="1" />
          <rect className="px-o" x="6" y="11" width="3" height="1" />
          <rect className="px-x" x="9" y="11" width="1" height="1" />
          <rect className="px-o" x="10" y="11" width="2" height="1" />
          <rect className="px-x" x="12" y="11" width="1" height="1" />
          <rect className="px-x" x="3" y="12" width="2" height="1" />
          <rect className="px-x" x="6" y="12" width="1" height="1" />
          <rect className="px-o" x="7" y="12" width="1" height="1" />
          <rect className="px-x" x="8" y="12" width="1" height="1" />
          <rect className="px-x" x="10" y="12" width="2" height="1" />
          <rect className="px-x" x="6" y="13" width="3" height="1" />
        </svg>;
default:return null;}}
