import {createContext,useContext,useLayoutEffect,useRef,useState} from 'react';
import type {ReactNode} from 'react';
import {flushSync} from 'react-dom';
import type {ChatCharacter} from '../types/chatCharacters';
import type {ChatPreferences} from '../types/chatPreferences';
import {DEFAULT_AVATAR} from '../utils/defaultAvatar';
interface IdentityView {text:Record<string,string>;attributes:Record<string,Record<string,string>>;bars:{width:string;marginRight:string}[];barcodeSet:boolean;}
export interface ChatIdentityApi {room(character:ChatCharacter):void;settings(profile:ChatCharacter|null,avatar:string,name:string):void;summaries(preferences:ChatPreferences):void;}
const Context=createContext<{view:IdentityView;api:ChatIdentityApi}|null>(null);
export function ChatIdentityProvider({children}:{children:ReactNode}){const [view,setView]=useState<IdentityView>({text:{},attributes:{},bars:[],barcodeSet:false});const state=useRef(view);function update(patch:Partial<IdentityView>){state.current={...state.current,...patch};flushSync(()=>setView(state.current));}const api=useRef<ChatIdentityApi|null>(null);
 if(!api.current)api.current={room(character){const avatar=character.photoUrl||DEFAULT_AVATAR;update({text:{...state.current.text,chatRoomName:String(character.name||character.nickname||'未命名角色').trim()||'未命名角色'},attributes:{...state.current.attributes,chatRoomAvatar:{src:avatar},chatListAvatar:{src:avatar},chatMessageAvatar:{src:avatar}}});},settings(profile,avatar,name){const signature=String(profile?.quote||'').trim(),birthday=[String(profile?.birthday||'').trim(),String(profile?.constellation||'').trim()].filter(Boolean).join(' · ');let stamp='--';if(profile?.archivedAt){const date=new Date(profile.archivedAt as string|number);if(!Number.isNaN(date.getTime()))stamp=`${date.getFullYear()}/${String(date.getMonth()+1).padStart(2,'0')}/${String(date.getDate()).padStart(2,'0')}`;}const digits=String(profile?.archivedAt||'').slice(0,10).replace(/\D/g,''),code=(digits||'00000000').slice(0,8);let seed=7;for(const ch of String(profile?.archiveId||'')+String(profile?.name||''))seed=(seed*31+ch.charCodeAt(0))>>>0;for(const ch of code)seed=(seed*31+ch.charCodeAt(0))>>>0;const rnd=()=> (seed=(seed*1103515245+12345)>>>0)/4294967296,bars:number[][]=[];for(let i=0;i<30;i++)bars.push([1+Math.floor(rnd()*4),1+Math.floor(rnd()*3)]);bars[bars.length-1][1]=0;const total=bars.reduce((sum,[w,gap])=>sum+w+gap,0);
 update({text:{...state.current.text,chatSettingsName:name||'当前角色',chatSettingsCardRelation:String(profile?.relationship||'').trim()||'—',chatSettingsCardRole:birthday||'—',chatSettingsCardMBTI:String(profile?.mbti||'').trim()||'—',chatSettingsCardSecretMemo:signature||'—',chatSettingsArchiveTime:`ID: ${stamp}`,chatSettingsBarcodeCode:code},attributes:{...state.current.attributes,chatSettingsAvatar:{src:avatar},chatSettingsCardSecretMemo:{'data-title':signature}},bars:bars.map(([w,gap])=>({width:`${(w/total*100).toFixed(3)}%`,marginRight:`${(gap/total*100).toFixed(3)}%`})),barcodeSet:true});},summaries(preferences){update({text:{...state.current.text,chatSettingsReadSummary:`已读标记：${preferences.readReceipt?'开启':'关闭'}`,chatSettingsSegmentSummary:`分段回复：${preferences.segmented?'开启':'关闭'}`,chatSettingsDelaySummary:`回复间隔：${(preferences.segmentDelay/1000).toFixed(1)} 秒`}});}};
 useLayoutEffect(()=>{const connect=(event:Event)=>(event as CustomEvent<{accept(api:ChatIdentityApi):void}>).detail.accept(api.current!);window.addEventListener('qingtuan:chat-identity-connect',connect);return()=>window.removeEventListener('qingtuan:chat-identity-connect',connect);},[]);return <Context.Provider value={{view,api:api.current}}>{children}</Context.Provider>;}
export function useChatIdentity(){const value=useContext(Context);if(!value)throw Error('ChatIdentityProvider is required');return value;}
