import {writeSettingsBatch} from '../utils/settingsPersistence';
import { flushSync } from 'react-dom';
import { createContext, useContext, useEffect, useLayoutEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import type { VoiceConfig, ImageConfig, ImageCharacter } from '../types/voiceImage';
import { useSettingsNavigation } from './SettingsNavigationProvider';
import { useChoice } from './ChoiceProvider';
import { choiceMaps, IMAGE_MODEL_PRESETS, normalizeImageCharacters, normalizeModelOptions, filterFetchedModels, fetchGeminiModels, fetchOpenAICompatibleModels, synthesizeSpeech, testImage, loadVoiceImageSettings } from '../utils/voiceImageServices';
import { applyVoiceProviderPreset, applyImageProviderPreset } from '../utils/voiceImagePresets';
import { showToast } from '../utils/toast';
function cleanVoice(value:VoiceConfig):VoiceConfig{return {...value,transcriptionProvider:value.transcriptionProvider||'',transcriptionBaseUrl:value.transcriptionBaseUrl?.trim().replace(/\/+$/,'')||'',transcriptionApiKey:value.transcriptionApiKey?.trim()||'',transcriptionModel:value.transcriptionModel?.trim()||'',baseUrl:value.baseUrl.trim().replace(/\/+$/,''),apiKey:value.apiKey.trim(),model:value.model.trim(),voice:value.voice.trim(),format:value.format||'mp3',speed:Number(value.speed)||1};}
function cleanImage(value:ImageConfig):ImageConfig{return {...value,baseUrl:value.baseUrl.trim().replace(/\/+$/,''),apiKey:value.apiKey.trim(),model:value.model.trim(),size:value.size||'1024x1024',quality:value.quality||'auto',prompt:value.prompt.trim(),artistTags:value.artistTags.trim(),negativePrompt:value.negativePrompt.trim(),characters:normalizeImageCharacters(value.characters)};}
function useVoiceImageState(){
 const navigation=useSettingsNavigation(),choice=useChoice();
 const [initial]=useState(loadVoiceImageSettings),saved=useRef(initial),[voice,setVoice]=useState(initial.voice),[image,setImage]=useState(initial.image);
 const [pageOpen,setPageOpen]=useState(false),[tab,setTab]=useState('voice'),pageRef=useRef<HTMLDivElement>(null),contentRef=useRef<HTMLDivElement>(null);
 const [keysVisible,setKeysVisible]=useState({voice:false,image:false}),[fetching,setFetching]=useState({voice:false,image:false}),[testing,setTesting]=useState({voice:false,image:false}),[status,setStatus]=useState({voice:{message:'',type:''},image:{message:'',type:''}});
 const voiceMetaDefault=applyVoiceProviderPreset(voice,voice.provider).meta;
 const [voiceMeta,setVoiceMeta]=useState({...voiceMetaDefault,fetchDisabled:voice.provider==='grok',fetchLabel:'获取可用语音模型'});
 const [imageMeta,setImageMeta]=useState(applyImageProviderPreset(image,image.provider).meta);
 const [characterRevision,setCharacterRevision]=useState(0),[nameEdit,setNameEdit]=useState<{index:number;original:string;value:string}|null>(null);
 const audioRef=useRef<HTMLAudioElement>(null),[audioSrc,setAudioSrc]=useState(''),audioUrl=useRef(''),[audioState,setAudioState]=useState({current:0,duration:0,progress:0,playing:false,muted:false});
 const [imagePreview,setImagePreview]=useState<{src:string;objectUrl:string;model:string;description:string;shown:boolean}>({src:'',objectUrl:'',model:'',description:'',shown:false}),imageObjectUrl=useRef('');
 function readVoice(){return cleanVoice(voice);}function readImage(){return cleanImage(image);}
 function fill(){const next=loadVoiceImageSettings();saved.current=next;setVoice(next.voice);setImage(next.image);setNameEdit(null);setCharacterRevision(n=>n+1);setVoiceMeta({...applyVoiceProviderPreset(next.voice,next.voice.provider).meta,fetchDisabled:next.voice.provider==='grok',fetchLabel:'获取可用语音模型'});setImageMeta(applyImageProviderPreset(next.image,next.image.provider).meta);}
 useEffect(()=>navigation.registerDestination('settingVoiceAi',()=>{fill();setPageOpen(true);}),[navigation.registerDestination]);
 useEffect(()=>{const close=()=>setPageOpen(false);window.addEventListener('qingtuan:close-settings',close);return()=>window.removeEventListener('qingtuan:close-settings',close);},[]);
 function closePage(){if(document.activeElement instanceof HTMLElement&&pageRef.current?.contains(document.activeElement))document.activeElement.blur();setPageOpen(false);}
 function changeTab(value:string){setTab(value);if(contentRef.current)contentRef.current.scrollTop=0;}
 function setVoiceField<K extends keyof VoiceConfig>(key:K,value:VoiceConfig[K]){setVoice(current=>({...current,[key]:value}));}
 function setImageField<K extends keyof ImageConfig>(key:K,value:ImageConfig[K]){setImage(current=>({...current,[key]:value}));}
 function provider(kind:'voice'|'image',value:string){if(kind==='voice'){const result=applyVoiceProviderPreset(voice,value,true);setVoice(result.next);setVoiceMeta(result.meta);}else{const result=applyImageProviderPreset(image,value,true);setImage(result.next);setImageMeta(result.meta);}}
 function openChoice(kind:'voice'|'image',key:'provider'|'format'|'size'|'quality',type:string,title:string){const config=kind==='voice'?voice:image;const selected=String(config[key as keyof typeof config]||'');choice.openChoice({title,options:choiceMaps[type]||[],selected,confirm:value=>{if(key==='provider')provider(kind,value);else if(kind==='voice')setVoiceField('format',value);else if(key==='size'||key==='quality')setImageField(key,value);}});}
 function setKindStatus(kind:'voice'|'image',message='',type=''){setStatus(current=>({...current,[kind]:{message,type}}));}
 function commit(kind:'voice'|'image',config:VoiceConfig|ImageConfig){
  const next={...saved.current,[kind]:config};
  try{writeSettingsBatch({'smallphone_voice_image_settings_v1':JSON.stringify(next)});saved.current=next;setKindStatus(kind);return true;}
  catch(error){setKindStatus(kind,error instanceof Error?error.message:'保存失败','error');return false;}
 }
 function save(kind:'voice'|'image',notify=true){const ok=commit(kind,kind==='voice'?readVoice():readImage());if(ok&&notify)showToast(kind==='voice'?'语音设置已保存':'生图设置已保存');return ok;}
 function toggleEnabled(kind:'voice'|'image',value:boolean){
  const next=kind==='voice'?cleanVoice({...voice,enabled:value}):cleanImage({...image,enabled:value});
  if(!commit(kind,next))return;
  if(kind==='voice')setVoice(next as VoiceConfig);else setImage(next as ImageConfig);
 }
 async function fetchModels(kind:'voice'|'image'){setFetching(current=>({...current,[kind]:true}));const config=kind==='voice'?voice:image;try{let models:string[],message:string;if(kind==='image'&&config.provider==='novelai'){models=IMAGE_MODEL_PRESETS.novelai||[];message=`已载入 ${models.length} 个 NAI 模型`;}else{const base=config.baseUrl.trim(),key=config.apiKey.trim();if(!base||!key)throw Error('请先填写正确的 API 地址和 Key');const fetched=await(config.provider==='gemini'?fetchGeminiModels(base,key):fetchOpenAICompatibleModels(base,key));models=filterFetchedModels(fetched,kind,config.provider);if(!models.length)throw Error(kind==='voice'?'没有拉取到可用语音模型':'没有拉取到可用图片模型');message=`已获取 ${models.length} 个可用模型`;}setKindStatus(kind,message,'ok');choice.openChoice({title:kind==='voice'?'选择语音模型':'选择图片模型',options:normalizeModelOptions(models),selected:config.model,confirm:value=>kind==='voice'?setVoiceField('model',value):setImageField('model',value)});}catch(error){showToast(error instanceof Error?error.message:'获取模型失败');setKindStatus(kind);}finally{setFetching(current=>({...current,[kind]:false}));if(kind==='voice')setVoiceMeta(current=>({...current,fetchDisabled:false}));}}
 function syncAudio(){const audio=audioRef.current;if(!audio)return;const current=Number.isFinite(audio.currentTime)?audio.currentTime:0,duration=Number.isFinite(audio.duration)?audio.duration:0;setAudioState({current,duration,progress:duration>0?Math.round(current/duration*1000):0,playing:!audio.paused&&!audio.ended,muted:audio.muted||audio.volume===0});}
 async function attachAudio(blob:Blob){if(audioUrl.current.startsWith('blob:'))URL.revokeObjectURL(audioUrl.current);audioUrl.current=URL.createObjectURL(blob);flushSync(()=>setAudioSrc(audioUrl.current));const audio=audioRef.current;if(!audio)return;audio.load();syncAudio();try{await audio.play();}catch{}syncAudio();}
 async function test(kind:'voice'|'image'){if(testing[kind])return;setTesting(current=>({...current,[kind]:true}));setKindStatus(kind);try{if(kind==='voice'){const blob=await synthesizeSpeech(readVoice(),'你好，这是一段青团机的语音试听。');await attachAudio(blob);}else{const cfg=readImage(),result=await testImage(cfg);if(!result)return;let src:string;if('blob'in result){if(imageObjectUrl.current)URL.revokeObjectURL(imageObjectUrl.current);imageObjectUrl.current=URL.createObjectURL(result.blob);src=imageObjectUrl.current;}else src=result.src;const quality=choiceMaps.quality?.find(item=>item.value===cfg.quality)?.label||cfg.quality||'';setImagePreview({src,objectUrl:imageObjectUrl.current,model:quality?`${cfg.model} · ${quality}`:cfg.model,description:cfg.prompt||'',shown:true});}showToast(kind==='voice'?'语音测试成功':'生图测试成功');}catch(error){const raw=error instanceof Error?error.message:kind==='voice'?'语音测试失败':'生图测试失败';showToast(raw.includes('Failed to fetch')?'连接失败，请检查接口地址、Key 或浏览器跨域限制':raw);}finally{setTesting(current=>({...current,[kind]:false}));}}
 function updateCharacter(index:number,key:keyof ImageCharacter,value:string){setImage(current=>({...current,characters:current.characters.map((character,i)=>i===index?{...character,[key]:value}:character)}));}
 function rebuildCharacters(characters:ImageCharacter[]){setImage(current=>({...current,characters:normalizeImageCharacters(characters)}));setNameEdit(null);setCharacterRevision(n=>n+1);}
 function addCharacter(){if(image.characters.length>=3)return;rebuildCharacters([...image.characters,{role:'chat',name:`角色 ${image.characters.length}`,prompt:'',negativePrompt:''}]);}
 function finishName(cancel=false){if(!nameEdit)return;const value=(cancel?nameEdit.original:nameEdit.value).trim()||(nameEdit.index===0?'屏幕前的你':`角色 ${nameEdit.index}`);rebuildCharacters(image.characters.map((character,i)=>i===nameEdit.index?{...character,name:value}:character));}
 // 未迁移聊天模块暂时使用此服务入口；聊天迁移后移除兼容入口。
 useLayoutEffect(()=>{window.smallphoneVoiceReady=()=>{const cfg=saved.current.voice;return !!(cfg.enabled&&cfg.baseUrl&&cfg.apiKey&&(cfg.voice||cfg.provider==='grok'));};window.smallphoneSynthesizeSpeech=async text=>window.smallphoneVoiceReady?.()?synthesizeSpeech(cleanVoice(saved.current.voice),text):null;window.smallphoneMediaServices={getVoiceConfig:()=>({...loadVoiceImageSettings().voice}),getImageConfig:()=>({...loadVoiceImageSettings().image}),isVoiceEnabled:()=>!!loadVoiceImageSettings().voice.enabled,isImageEnabled:()=>!!loadVoiceImageSettings().image.enabled};return()=>{delete window.smallphoneVoiceReady;delete window.smallphoneSynthesizeSpeech;delete window.smallphoneMediaServices;};},[]);
 return{voice,image,pageOpen,pageRef,contentRef,closePage,tab,changeTab,voiceMeta,imageMeta,keysVisible,toggleKey:(kind:'voice'|'image')=>setKeysVisible(current=>({...current,[kind]:!current[kind]})),fetching,testing,status,setVoiceField,setImageField,provider,openChoice,save,toggleEnabled,fetchModels,test,audioRef,audioSrc,audioState,syncAudio,toggleAudio:async()=>{const audio=audioRef.current;if(!audio?.src)return;if(audio.paused)try{await audio.play();}catch{showToast('播放失败');}else audio.pause();syncAudio();},seekAudio:(value:number)=>{const audio=audioRef.current;if(!audio?.duration||!Number.isFinite(audio.duration))return;audio.currentTime=value/1000*audio.duration;syncAudio();},toggleMute:()=>{if(audioRef.current)audioRef.current.muted=!audioRef.current.muted;syncAudio();},imagePreview,characterRevision,nameEdit,setNameEdit,updateCharacter,addCharacter,removeCharacter:(index:number)=>rebuildCharacters(image.characters.filter((_,i)=>i!==index)),finishName};
}
const Context=createContext<ReturnType<typeof useVoiceImageState>|null>(null);
export function VoiceImageProvider({children}:{children:ReactNode}){const value=useVoiceImageState();return <Context.Provider value={value}>{children}</Context.Provider>;}
export function useVoiceImage(){const value=useContext(Context);if(!value)throw Error('VoiceImageProvider is required');return value;}
