import { useEffect, useRef, useState } from 'react';
import type { PointerEvent as ReactPointerEvent } from 'react';
import type { WorldEntry } from '../types/world';
import { useWorld } from '../providers/WorldProvider';
import { showToast } from '../utils/toast';
type EntryItem={entry:WorldEntry;index:number};
type Drag={id:string;origin:number;order:string[];left:number;top:number;width:number;height:number;offset:number;layout:({id:string}|{text:string;key:string})[];buttonPressed:boolean};
/** 条目排序由状态管理，浮动副本通过 React portal 保持世界书的样式范围。 */
export function useWorldEntrySort(filtered:EntryItem[]){const world=useWorld(),rows=useRef(new Map<string,HTMLDivElement>()),live=useRef<Drag|null>(null),[drag,setDrag]=useState<Drag|null>(null),hold=useRef<ReturnType<typeof setTimeout>|null>(null),press=useRef({x:0,y:0,pointer:0,touch:false,buttonPressed:false}),snapshot=useRef(filtered);
 function clearHold(){if(hold.current!==null){clearTimeout(hold.current);hold.current=null;}}
 function start(id:string,x:number,y:number){if(live.current)return;const row=rows.current.get(id);if(!row)return;const rect=row.getBoundingClientRect(),order=filtered.map(item=>item.entry.id);snapshot.current=filtered;try{row.setPointerCapture(press.current.pointer);}catch{}const next={id,origin:order.indexOf(id),order,left:rect.left,top:rect.top,width:rect.width,height:rect.height,offset:y-rect.top,buttonPressed:press.current.buttonPressed,layout:[{text:"\n        ",key:"start"},...order.flatMap((id,index)=>[{id},{text:index<order.length-1?"\n      \n        ":"\n      ",key:"gap"+index}])]};live.current=next;setDrag(next);world.suppressEntryClickUntil.current=Date.now()+1000;navigator.vibrate?.(10);}
 function down(id:string,event:ReactPointerEvent<HTMLDivElement>){if(event.button!==0||world.entrySearch.trim()||world.entryFilter!=='all'||filtered.length<2||(event.target as Element).closest('.world-entry-copy,.world-entry-controls,input'))return;clearHold();press.current={x:event.pointerType==='mouse'?Math.floor(event.clientX):event.clientX,y:event.pointerType==='mouse'?Math.floor(event.clientY):event.clientY,pointer:event.pointerId,touch:event.pointerType==='touch',buttonPressed:!!(event.target as Element).closest('.world-book-open')};hold.current=setTimeout(()=>{hold.current=null;start(id,press.current.x,press.current.y);},380);}
 function move(event:Pick<PointerEvent,"pointerId"|"clientX"|"clientY"|"preventDefault">){if(event.pointerId!==press.current.pointer)return;const current=live.current;if(!current){if(Math.hypot(event.clientX-press.current.x,event.clientY-press.current.y)>(press.current.touch?9:8))clearHold();return;}event.preventDefault();const y=press.current.touch?event.clientY:Math.floor(event.clientY);const others=current.order.filter(id=>id!==current.id),target=others.find(id=>{const rect=rows.current.get(id)?.getBoundingClientRect();return rect&&y<rect.top+rect.height/2;}),order=[...others];order.splice(target?order.indexOf(target):order.length,0,current.id);const layout=current.layout.filter(token=>!('id' in token&&token.id===current.id));const at=target?layout.findIndex(token=>'id' in token&&token.id===target):layout.length;layout.splice(at,0,{id:current.id});const active=rows.current.get(current.id)?.contains(document.activeElement)?document.activeElement:null;if(active instanceof HTMLElement)active.blur();const next={...current,order,layout,top:y-current.offset};live.current=next;setDrag(next);const page=world.pageRef.current,rect=page?.getBoundingClientRect();if(page&&rect){if(event.clientY<rect.top+75)page.scrollTop-=10;else if(event.clientY>rect.bottom-75)page.scrollTop+=10;}}
 function finish(){clearHold();const current=live.current;if(!current)return;live.current=null;setDrag(null);world.suppressEntryClickUntil.current=Date.now()+650;const book=world.liveBooks.current.find(value=>value.id===world.bookId);if(!book)return;const entries=current.order.map(id=>book.entries.find(entry=>entry.id===id)).filter((entry):entry is WorldEntry=>!!entry);if(entries.length===book.entries.length&&current.order[current.origin]!==undefined&&current.order.indexOf(current.id)!==current.origin){if(!world.commit(world.liveBooks.current.map(value=>value.id===world.bookId?{...value,entries}:value)))return;world.rerender('book');showToast('条目顺序已更新');}}
 useEffect(()=>{if(!drag)return;const up=()=>finish(),outsideMove=(event:PointerEvent)=>{if(![...rows.current.values()].some(row=>row.contains(event.target as Node)))move(event);};document.addEventListener("pointermove",outsideMove);document.addEventListener("pointerup",up);document.addEventListener("pointercancel",up);return()=>{document.removeEventListener("pointermove",outsideMove);document.removeEventListener("pointerup",up);document.removeEventListener("pointercancel",up);};},[!!drag]);
 useEffect(()=>()=>{clearHold();},[]);useEffect(()=>{clearHold();live.current=null;setDrag(null);},[world.bookId,world.revision,world.entrySearch,world.entryFilter]);
 return{drag,items:drag?drag.order.map(id=>snapshot.current.find(item=>item.entry.id===id)!).filter(Boolean):filtered,ghost:drag?snapshot.current.find(item=>item.entry.id===drag.id):undefined,bind:(id:string)=>({ref:(row:HTMLDivElement|null)=>{if(row)rows.current.set(id,row);else rows.current.delete(id);},onPointerDown:(event:ReactPointerEvent<HTMLDivElement>)=>down(id,event),onPointerMove:move,onPointerLeave:()=>{if(!live.current)clearHold();},onPointerUp:finish,onPointerCancel:finish,onContextMenu:(event:React.MouseEvent<HTMLDivElement>)=>{if(live.current||hold.current!==null)event.preventDefault();}})};
}
